name: Main workflow
on: [push]
jobs:
  test_job:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/grcov@v0.1
      - name: codecov
        run: |-
          zip -0 ccov.zip `find . \( -name "rustexample*.gc*" \) -print`
          grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info
          bash <(curl -s https://codecov.io/bash) -f lcov.info
